apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: sandbox-preview-env
resources:
- ../base
replicas:
- name: nginx-deployment
  count: 3
images:
- name: nginx
  newTag: 1.14.2
