apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: preview
  namespace: argocd
spec:
  description: Project for creating preview env based on PR
  destinations:
  - namespace: 'pr-*'
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/Aamir-raza-1/preview
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
